version: '3'

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    hostname: db
    environment:
      - MYSQL_DATABASE=people
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    networks:
      - my-net

  app:
    build:
      context: ./node
    image: docker-challenge-nodejs
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    hostname: nodejs
    depends_on:
      - db
    networks:
      - my-net

  reverse_proxy:
    build:
      context: ./nginx
    image: docker-challenge-nginx
    container_name: nginx
    hostname: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
     - my-net

networks:
  my-net:
    name: nginx-nodejs-challenge
    driver: bridge
